"""add mata_kuliah table

Revision ID: 174492167281
Revises: 4028c6b5f123
Create Date: 2025-06-11 05:43:22.691154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174492167281'
down_revision = '4028c6b5f123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mata_kuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mata_kuliah')
    # ### end Alembic commands ###
