"""initial migration

Revision ID: 4028c6b5f123
Revises: 
Create Date: 2025-06-10 21:29:08.195876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4028c6b5f123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('nip', sa.String(length=30), nullable=False),
    sa.Column('prodi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaksi_id'))

    op.drop_table('transaksi')
    with op.batch_alter_table('mata_kuliah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mata_kuliah_id'))
        batch_op.drop_index(batch_op.f('ix_mata_kuliah_kode_mk'))

    op.drop_table('mata_kuliah')
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nim',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_mahasiswa_id'))
        batch_op.drop_index(batch_op.f('ix_mahasiswa_nama'))
        batch_op.drop_column('umur')
        batch_op.drop_column('kota_asal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kota_asal', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('umur', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_mahasiswa_nama'), ['nama'], unique=False)
        batch_op.create_index(batch_op.f('ix_mahasiswa_id'), ['id'], unique=False)
        batch_op.alter_column('nim',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    op.create_table('mata_kuliah',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('kode_mk', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nama_mk', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mata_kuliah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mata_kuliah_kode_mk'), ['kode_mk'], unique=True)
        batch_op.create_index(batch_op.f('ix_mata_kuliah_id'), ['id'], unique=False)

    op.create_table('transaksi',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mahasiswa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mata_kuliah_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('semester', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], name=op.f('transaksi_ibfk_1')),
    sa.ForeignKeyConstraint(['mata_kuliah_id'], ['mata_kuliah.id'], name=op.f('transaksi_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaksi_id'), ['id'], unique=False)

    op.drop_table('dosen')
    # ### end Alembic commands ###
