"""init

Revision ID: 7c2a6586bc43
Revises: 
Create Date: 2025-06-11 22:25:31.424979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c2a6586bc43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaksi_id'))

    op.drop_table('transaksi')
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurusan', sa.String(length=50), nullable=False))
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nim',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_mahasiswa_id'))
        batch_op.drop_index(batch_op.f('ix_mahasiswa_nama'))
        batch_op.drop_column('kota_asal')
        batch_op.drop_column('umur')

    with op.batch_alter_table('mata_kuliah', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('nama', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sks', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_mata_kuliah_id'))
        batch_op.drop_index(batch_op.f('ix_mata_kuliah_kode_mk'))
        batch_op.create_unique_constraint(None, ['kode'])
        batch_op.drop_column('nama_mk')
        batch_op.drop_column('kode_mk')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mata_kuliah', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode_mk', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('nama_mk', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_mata_kuliah_kode_mk'), ['kode_mk'], unique=True)
        batch_op.create_index(batch_op.f('ix_mata_kuliah_id'), ['id'], unique=False)
        batch_op.drop_column('sks')
        batch_op.drop_column('nama')
        batch_op.drop_column('kode')

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('umur', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kota_asal', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_mahasiswa_nama'), ['nama'], unique=False)
        batch_op.create_index(batch_op.f('ix_mahasiswa_id'), ['id'], unique=False)
        batch_op.alter_column('nim',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('jurusan')

    op.create_table('transaksi',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mahasiswa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mata_kuliah_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('semester', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaksi_id'), ['id'], unique=False)

    # ### end Alembic commands ###
